/* 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Other licenses:
 * -----------------------------------------------------------------------------
 * Commercial licenses for this work are available. These replace the above
 * ASL 2.0 and offer limited warranties, support, maintenance, and commercial
 * database integrations.
 *
 * For more information, please visit: http://www.jooq.org/licenses
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */
package org.jooq.example.testcontainers.db.tables;

import java.time.LocalDateTime;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.example.testcontainers.db.Keys;
import org.jooq.example.testcontainers.db.Public;
import org.jooq.example.testcontainers.db.tables.records.LanguageRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Language extends TableImpl<LanguageRecord> {

  private static final long serialVersionUID = 1L;

  /** The reference instance of <code>public.language</code> */
  public static final Language LANGUAGE = new Language();

  /** The class holding records for this type */
  @Override
  public Class<LanguageRecord> getRecordType() {
    return LanguageRecord.class;
  }

  /** The column <code>public.language.language_id</code>. */
  public final TableField<LanguageRecord, Long> LANGUAGE_ID =
      createField(
          DSL.name("language_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

  /** The column <code>public.language.name</code>. */
  public final TableField<LanguageRecord, String> NAME =
      createField(DSL.name("name"), SQLDataType.CHAR(20).nullable(false), this, "");

  /** The column <code>public.language.last_update</code>. */
  public final TableField<LanguageRecord, LocalDateTime> LAST_UPDATE =
      createField(
          DSL.name("last_update"),
          SQLDataType.LOCALDATETIME(6)
              .nullable(false)
              .defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)),
          this,
          "");

  private Language(Name alias, Table<LanguageRecord> aliased) {
    this(alias, aliased, null);
  }

  private Language(Name alias, Table<LanguageRecord> aliased, Field<?>[] parameters) {
    super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
  }

  /** Create an aliased <code>public.language</code> table reference */
  public Language(String alias) {
    this(DSL.name(alias), LANGUAGE);
  }

  /** Create an aliased <code>public.language</code> table reference */
  public Language(Name alias) {
    this(alias, LANGUAGE);
  }

  /** Create a <code>public.language</code> table reference */
  public Language() {
    this(DSL.name("language"), null);
  }

  public <O extends Record> Language(Table<O> child, ForeignKey<O, LanguageRecord> key) {
    super(child, key, LANGUAGE);
  }

  @Override
  public Schema getSchema() {
    return aliased() ? null : Public.PUBLIC;
  }

  @Override
  public Identity<LanguageRecord, Long> getIdentity() {
    return (Identity<LanguageRecord, Long>) super.getIdentity();
  }

  @Override
  public UniqueKey<LanguageRecord> getPrimaryKey() {
    return Keys.LANGUAGE_PKEY;
  }

  @Override
  public Language as(String alias) {
    return new Language(DSL.name(alias), this);
  }

  @Override
  public Language as(Name alias) {
    return new Language(alias, this);
  }

  /** Rename this table */
  @Override
  public Language rename(String name) {
    return new Language(DSL.name(name), null);
  }

  /** Rename this table */
  @Override
  public Language rename(Name name) {
    return new Language(name, null);
  }

  // -------------------------------------------------------------------------
  // Row3 type methods
  // -------------------------------------------------------------------------

  @Override
  public Row3<Long, String, LocalDateTime> fieldsRow() {
    return (Row3) super.fieldsRow();
  }
}
