/* 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Other licenses:
 * -----------------------------------------------------------------------------
 * Commercial licenses for this work are available. These replace the above
 * ASL 2.0 and offer limited warranties, support, maintenance, and commercial
 * database integrations.
 *
 * For more information, please visit: http://www.jooq.org/licenses
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */
package org.jooq.meta.postgres.pg_catalog.tables;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.meta.postgres.pg_catalog.PgCatalog;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PgAttrdef extends TableImpl<Record> {

  private static final long serialVersionUID = 1L;

  /** The reference instance of <code>pg_catalog.pg_attrdef</code> */
  public static final PgAttrdef PG_ATTRDEF = new PgAttrdef();

  /** The class holding records for this type */
  @Override
  public Class<Record> getRecordType() {
    return Record.class;
  }

  /** The column <code>pg_catalog.pg_attrdef.oid</code>. */
  public final TableField<Record, Long> OID =
      createField(DSL.name("oid"), SQLDataType.BIGINT.nullable(false), this, "");

  /** The column <code>pg_catalog.pg_attrdef.adrelid</code>. */
  public final TableField<Record, Long> ADRELID =
      createField(DSL.name("adrelid"), SQLDataType.BIGINT.nullable(false), this, "");

  /** The column <code>pg_catalog.pg_attrdef.adnum</code>. */
  public final TableField<Record, Short> ADNUM =
      createField(DSL.name("adnum"), SQLDataType.SMALLINT.nullable(false), this, "");

  /**
   * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify
   *     how this type should be handled. Deprecation can be turned off using {@literal
   *     <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  public final TableField<Record, Object> ADBIN =
      createField(
          DSL.name("adbin"),
          org.jooq.impl.DefaultDataType.getDefaultDataType("\"pg_catalog\".\"pg_node_tree\"")
              .nullable(false),
          this,
          "");

  private PgAttrdef(Name alias, Table<Record> aliased) {
    this(alias, aliased, null);
  }

  private PgAttrdef(Name alias, Table<Record> aliased, Field<?>[] parameters) {
    super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
  }

  /** Create an aliased <code>pg_catalog.pg_attrdef</code> table reference */
  public PgAttrdef(String alias) {
    this(DSL.name(alias), PG_ATTRDEF);
  }

  /** Create an aliased <code>pg_catalog.pg_attrdef</code> table reference */
  public PgAttrdef(Name alias) {
    this(alias, PG_ATTRDEF);
  }

  /** Create a <code>pg_catalog.pg_attrdef</code> table reference */
  public PgAttrdef() {
    this(DSL.name("pg_attrdef"), null);
  }

  public <O extends Record> PgAttrdef(Table<O> child, ForeignKey<O, Record> key) {
    super(child, key, PG_ATTRDEF);
  }

  @Override
  public Schema getSchema() {
    return aliased() ? null : PgCatalog.PG_CATALOG;
  }

  @Override
  public PgAttrdef as(String alias) {
    return new PgAttrdef(DSL.name(alias), this);
  }

  @Override
  public PgAttrdef as(Name alias) {
    return new PgAttrdef(alias, this);
  }

  /** Rename this table */
  @Override
  public PgAttrdef rename(String name) {
    return new PgAttrdef(DSL.name(name), null);
  }

  /** Rename this table */
  @Override
  public PgAttrdef rename(Name name) {
    return new PgAttrdef(name, null);
  }
}
