/* 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Other licenses:
 * -----------------------------------------------------------------------------
 * Commercial licenses for this work are available. These replace the above
 * ASL 2.0 and offer limited warranties, support, maintenance, and commercial
 * database integrations.
 *
 * For more information, please visit: http://www.jooq.org/licenses
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */
package org.jooq.meta.postgres.pg_catalog.tables;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.meta.postgres.pg_catalog.PgCatalog;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PgDescription extends TableImpl<Record> {

  private static final long serialVersionUID = 1L;

  /** The reference instance of <code>pg_catalog.pg_description</code> */
  public static final PgDescription PG_DESCRIPTION = new PgDescription();

  /** The class holding records for this type */
  @Override
  public Class<Record> getRecordType() {
    return Record.class;
  }

  /** The column <code>pg_catalog.pg_description.objoid</code>. */
  public final TableField<Record, Long> OBJOID =
      createField(DSL.name("objoid"), SQLDataType.BIGINT.nullable(false), this, "");

  /** The column <code>pg_catalog.pg_description.classoid</code>. */
  public final TableField<Record, Long> CLASSOID =
      createField(DSL.name("classoid"), SQLDataType.BIGINT.nullable(false), this, "");

  /** The column <code>pg_catalog.pg_description.objsubid</code>. */
  public final TableField<Record, Integer> OBJSUBID =
      createField(DSL.name("objsubid"), SQLDataType.INTEGER.nullable(false), this, "");

  /** The column <code>pg_catalog.pg_description.description</code>. */
  public final TableField<Record, String> DESCRIPTION =
      createField(DSL.name("description"), SQLDataType.CLOB.nullable(false), this, "");

  private PgDescription(Name alias, Table<Record> aliased) {
    this(alias, aliased, null);
  }

  private PgDescription(Name alias, Table<Record> aliased, Field<?>[] parameters) {
    super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
  }

  /** Create an aliased <code>pg_catalog.pg_description</code> table reference */
  public PgDescription(String alias) {
    this(DSL.name(alias), PG_DESCRIPTION);
  }

  /** Create an aliased <code>pg_catalog.pg_description</code> table reference */
  public PgDescription(Name alias) {
    this(alias, PG_DESCRIPTION);
  }

  /** Create a <code>pg_catalog.pg_description</code> table reference */
  public PgDescription() {
    this(DSL.name("pg_description"), null);
  }

  public <O extends Record> PgDescription(Table<O> child, ForeignKey<O, Record> key) {
    super(child, key, PG_DESCRIPTION);
  }

  @Override
  public Schema getSchema() {
    return aliased() ? null : PgCatalog.PG_CATALOG;
  }

  @Override
  public PgDescription as(String alias) {
    return new PgDescription(DSL.name(alias), this);
  }

  @Override
  public PgDescription as(Name alias) {
    return new PgDescription(alias, this);
  }

  /** Rename this table */
  @Override
  public PgDescription rename(String name) {
    return new PgDescription(DSL.name(name), null);
  }

  /** Rename this table */
  @Override
  public PgDescription rename(Name name) {
    return new PgDescription(name, null);
  }
}
