/* 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Other licenses:
 * -----------------------------------------------------------------------------
 * Commercial licenses for this work are available. These replace the above
 * ASL 2.0 and offer limited warranties, support, maintenance, and commercial
 * database integrations.
 *
 * For more information, please visit: http://www.jooq.org/licenses
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */
package org.jooq.meta.postgres.pg_catalog.tables;

import java.util.Arrays;
import java.util.List;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.meta.postgres.pg_catalog.Keys;
import org.jooq.meta.postgres.pg_catalog.PgCatalog;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PgEnum extends TableImpl<Record> {

  private static final long serialVersionUID = 1L;

  /** The reference instance of <code>pg_catalog.pg_enum</code> */
  public static final PgEnum PG_ENUM = new PgEnum();

  /** The class holding records for this type */
  @Override
  public Class<Record> getRecordType() {
    return Record.class;
  }

  /** The column <code>pg_catalog.pg_enum.oid</code>. */
  public final TableField<Record, Long> OID =
      createField(DSL.name("oid"), SQLDataType.BIGINT.nullable(false), this, "");

  /** The column <code>pg_catalog.pg_enum.enumtypid</code>. */
  public final TableField<Record, Long> ENUMTYPID =
      createField(DSL.name("enumtypid"), SQLDataType.BIGINT.nullable(false), this, "");

  /** The column <code>pg_catalog.pg_enum.enumsortorder</code>. */
  public final TableField<Record, Float> ENUMSORTORDER =
      createField(DSL.name("enumsortorder"), SQLDataType.REAL.nullable(false), this, "");

  /** The column <code>pg_catalog.pg_enum.enumlabel</code>. */
  public final TableField<Record, String> ENUMLABEL =
      createField(DSL.name("enumlabel"), SQLDataType.VARCHAR.nullable(false), this, "");

  private PgEnum(Name alias, Table<Record> aliased) {
    this(alias, aliased, null);
  }

  private PgEnum(Name alias, Table<Record> aliased, Field<?>[] parameters) {
    super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
  }

  /** Create an aliased <code>pg_catalog.pg_enum</code> table reference */
  public PgEnum(String alias) {
    this(DSL.name(alias), PG_ENUM);
  }

  /** Create an aliased <code>pg_catalog.pg_enum</code> table reference */
  public PgEnum(Name alias) {
    this(alias, PG_ENUM);
  }

  /** Create a <code>pg_catalog.pg_enum</code> table reference */
  public PgEnum() {
    this(DSL.name("pg_enum"), null);
  }

  public <O extends Record> PgEnum(Table<O> child, ForeignKey<O, Record> key) {
    super(child, key, PG_ENUM);
  }

  @Override
  public Schema getSchema() {
    return aliased() ? null : PgCatalog.PG_CATALOG;
  }

  @Override
  public List<ForeignKey<Record, ?>> getReferences() {
    return Arrays.asList(Keys.PG_ENUM__SYNTHETIC_FK_PG_ENUM__SYNTHETIC_PK_PG_TYPE);
  }

  private transient PgType _pgType;

  public PgType pgType() {
    if (_pgType == null)
      _pgType = new PgType(this, Keys.PG_ENUM__SYNTHETIC_FK_PG_ENUM__SYNTHETIC_PK_PG_TYPE);
    return _pgType;
  }

  @Override
  public PgEnum as(String alias) {
    return new PgEnum(DSL.name(alias), this);
  }

  @Override
  public PgEnum as(Name alias) {
    return new PgEnum(alias, this);
  }

  /** Rename this table */
  @Override
  public PgEnum rename(String name) {
    return new PgEnum(DSL.name(name), null);
  }

  /** Rename this table */
  @Override
  public PgEnum rename(Name name) {
    return new PgEnum(name, null);
  }
}
