/* 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Other licenses:
 * -----------------------------------------------------------------------------
 * Commercial licenses for this work are available. These replace the above
 * ASL 2.0 and offer limited warranties, support, maintenance, and commercial
 * database integrations.
 *
 * For more information, please visit: http://www.jooq.org/licenses
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */
package org.jooq.example.testcontainers.db.routines;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.example.testcontainers.db.Public;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class InventoryHeldByCustomer extends AbstractRoutine<Integer> {

  private static final long serialVersionUID = 1L;

  /** The parameter <code>public.inventory_held_by_customer.RETURN_VALUE</code>. */
  public static final Parameter<Integer> RETURN_VALUE =
      Internal.createParameter("RETURN_VALUE", SQLDataType.INTEGER, false, false);

  /** The parameter <code>public.inventory_held_by_customer.p_inventory_id</code>. */
  public static final Parameter<Long> P_INVENTORY_ID =
      Internal.createParameter("p_inventory_id", SQLDataType.BIGINT, false, false);

  /** Create a new routine call instance */
  public InventoryHeldByCustomer() {
    super("inventory_held_by_customer", Public.PUBLIC, SQLDataType.INTEGER);

    setReturnParameter(RETURN_VALUE);
    addInParameter(P_INVENTORY_ID);
  }

  /** Set the <code>p_inventory_id</code> parameter IN value to the routine */
  public void setPInventoryId(Long value) {
    setValue(P_INVENTORY_ID, value);
  }

  /**
   * Set the <code>p_inventory_id</code> parameter to the function to be used with a {@link
   * org.jooq.Select} statement
   */
  public void setPInventoryId(Field<Long> field) {
    setField(P_INVENTORY_ID, field);
  }
}
