/* 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Other licenses:
 * -----------------------------------------------------------------------------
 * Commercial licenses for this work are available. These replace the above
 * ASL 2.0 and offer limited warranties, support, maintenance, and commercial
 * database integrations.
 *
 * For more information, please visit: http://www.jooq.org/licenses
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */
package org.jooq.meta.firebird.rdb.tables;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.meta.firebird.rdb.DefaultSchema;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Rdb$checkConstraints extends TableImpl<Record> {

  private static final long serialVersionUID = 1L;

  /** The reference instance of <code>RDB$CHECK_CONSTRAINTS</code> */
  public static final Rdb$checkConstraints RDB$CHECK_CONSTRAINTS = new Rdb$checkConstraints();

  /** The class holding records for this type */
  @Override
  public Class<Record> getRecordType() {
    return Record.class;
  }

  /** The column <code>RDB$CHECK_CONSTRAINTS.RDB$CONSTRAINT_NAME</code>. */
  public final TableField<Record, String> RDB$CONSTRAINT_NAME =
      createField(DSL.name("RDB$CONSTRAINT_NAME"), SQLDataType.CHAR(31), this, "");

  /** The column <code>RDB$CHECK_CONSTRAINTS.RDB$TRIGGER_NAME</code>. */
  public final TableField<Record, String> RDB$TRIGGER_NAME =
      createField(DSL.name("RDB$TRIGGER_NAME"), SQLDataType.CHAR(31), this, "");

  private Rdb$checkConstraints(Name alias, Table<Record> aliased) {
    this(alias, aliased, null);
  }

  private Rdb$checkConstraints(Name alias, Table<Record> aliased, Field<?>[] parameters) {
    super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
  }

  /** Create an aliased <code>RDB$CHECK_CONSTRAINTS</code> table reference */
  public Rdb$checkConstraints(String alias) {
    this(DSL.name(alias), RDB$CHECK_CONSTRAINTS);
  }

  /** Create an aliased <code>RDB$CHECK_CONSTRAINTS</code> table reference */
  public Rdb$checkConstraints(Name alias) {
    this(alias, RDB$CHECK_CONSTRAINTS);
  }

  /** Create a <code>RDB$CHECK_CONSTRAINTS</code> table reference */
  public Rdb$checkConstraints() {
    this(DSL.name("RDB$CHECK_CONSTRAINTS"), null);
  }

  public <O extends Record> Rdb$checkConstraints(Table<O> child, ForeignKey<O, Record> key) {
    super(child, key, RDB$CHECK_CONSTRAINTS);
  }

  @Override
  public Schema getSchema() {
    return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
  }

  @Override
  public Rdb$checkConstraints as(String alias) {
    return new Rdb$checkConstraints(DSL.name(alias), this);
  }

  @Override
  public Rdb$checkConstraints as(Name alias) {
    return new Rdb$checkConstraints(alias, this);
  }

  /** Rename this table */
  @Override
  public Rdb$checkConstraints rename(String name) {
    return new Rdb$checkConstraints(DSL.name(name), null);
  }

  /** Rename this table */
  @Override
  public Rdb$checkConstraints rename(Name name) {
    return new Rdb$checkConstraints(name, null);
  }
}
