/* 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Other licenses:
 * -----------------------------------------------------------------------------
 * Commercial licenses for this work are available. These replace the above
 * ASL 2.0 and offer limited warranties, support, maintenance, and commercial
 * database integrations.
 *
 * For more information, please visit: http://www.jooq.org/licenses
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */
package org.jooq.meta.cubrid.dba;

/** This class is generated by jOOQ. */
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class DefaultSchema extends org.jooq.impl.SchemaImpl {

  private static final long serialVersionUID = 191182248;

  /** The singleton instance of <code></code> */
  public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

  /** No further instances allowed */
  private DefaultSchema() {
    super("");
  }

  @Override
  public final java.util.List<org.jooq.Table<?>> getTables() {
    java.util.List result = new java.util.ArrayList();
    result.addAll(getTables0());
    return result;
  }

  private final java.util.List<org.jooq.Table<?>> getTables0() {
    return java.util.Arrays.<org.jooq.Table<?>>asList(
        org.jooq.meta.cubrid.dba.tables.DbAttribute.DB_ATTRIBUTE,
        org.jooq.meta.cubrid.dba.tables.DbClass.DB_CLASS,
        org.jooq.meta.cubrid.dba.tables.DbIndex.DB_INDEX,
        org.jooq.meta.cubrid.dba.tables.DbIndexKey.DB_INDEX_KEY,
        org.jooq.meta.cubrid.dba.tables.DbSerial.DB_SERIAL,
        org.jooq.meta.cubrid.dba.tables.DbUser.DB_USER);
  }
}
