/* 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Other licenses:
 * -----------------------------------------------------------------------------
 * Commercial licenses for this work are available. These replace the above
 * ASL 2.0 and offer limited warranties, support, maintenance, and commercial
 * database integrations.
 *
 * For more information, please visit: http://www.jooq.org/licenses
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */
package org.jooq.meta.cubrid.dba;

/**
 * This class is generated by jOOQ.
 *
 * <p>A class modelling foreign key relationships between tables of the <code></code> schema
 */
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

  // -------------------------------------------------------------------------
  // IDENTITY definitions
  // -------------------------------------------------------------------------

  // -------------------------------------------------------------------------
  // UNIQUE and PRIMARY KEY definitions
  // -------------------------------------------------------------------------

  public static final org.jooq.UniqueKey<org.jooq.Record> DB_SERIAL__PK_DB_SERIAL_NAME =
      UniqueKeys0.DB_SERIAL__PK_DB_SERIAL_NAME;

  // -------------------------------------------------------------------------
  // FOREIGN KEY definitions
  // -------------------------------------------------------------------------

  // -------------------------------------------------------------------------
  // [#1459] distribute members to avoid static initialisers > 64kb
  // -------------------------------------------------------------------------

  private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
    public static final org.jooq.UniqueKey<org.jooq.Record> DB_SERIAL__PK_DB_SERIAL_NAME =
        createUniqueKey(
            org.jooq.meta.cubrid.dba.tables.DbSerial.DB_SERIAL,
            org.jooq.meta.cubrid.dba.tables.DbSerial.DB_SERIAL.NAME);
  }
}
