/* 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Other licenses:
 * -----------------------------------------------------------------------------
 * Commercial licenses for this work are available. These replace the above
 * ASL 2.0 and offer limited warranties, support, maintenance, and commercial
 * database integrations.
 *
 * For more information, please visit: http://www.jooq.org/licenses
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */
package org.jooq.meta.cubrid.dba;

/**
 * This class is generated by jOOQ.
 *
 * <p>Convenience access to all tables in
 */
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

  /** The table db_attribute */
  public static final org.jooq.meta.cubrid.dba.tables.DbAttribute DB_ATTRIBUTE =
      org.jooq.meta.cubrid.dba.tables.DbAttribute.DB_ATTRIBUTE;

  /** The table db_class */
  public static final org.jooq.meta.cubrid.dba.tables.DbClass DB_CLASS =
      org.jooq.meta.cubrid.dba.tables.DbClass.DB_CLASS;

  /** The table db_index */
  public static final org.jooq.meta.cubrid.dba.tables.DbIndex DB_INDEX =
      org.jooq.meta.cubrid.dba.tables.DbIndex.DB_INDEX;

  /** The table db_index_key */
  public static final org.jooq.meta.cubrid.dba.tables.DbIndexKey DB_INDEX_KEY =
      org.jooq.meta.cubrid.dba.tables.DbIndexKey.DB_INDEX_KEY;

  /** The table db_serial */
  public static final org.jooq.meta.cubrid.dba.tables.DbSerial DB_SERIAL =
      org.jooq.meta.cubrid.dba.tables.DbSerial.DB_SERIAL;

  /** The table db_user */
  public static final org.jooq.meta.cubrid.dba.tables.DbUser DB_USER =
      org.jooq.meta.cubrid.dba.tables.DbUser.DB_USER;
}
