/* 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Other licenses:
 * -----------------------------------------------------------------------------
 * Commercial licenses for this work are available. These replace the above
 * ASL 2.0 and offer limited warranties, support, maintenance, and commercial
 * database integrations.
 *
 * For more information, please visit: http://www.jooq.org/licenses
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */
package org.jooq.meta.derby.sys;

import java.util.Arrays;
import java.util.List;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.jooq.meta.derby.sys.tables.Syschecks;
import org.jooq.meta.derby.sys.tables.Syscolumns;
import org.jooq.meta.derby.sys.tables.Sysconglomerates;
import org.jooq.meta.derby.sys.tables.Sysconstraints;
import org.jooq.meta.derby.sys.tables.Syskeys;
import org.jooq.meta.derby.sys.tables.Sysschemas;
import org.jooq.meta.derby.sys.tables.Syssequences;
import org.jooq.meta.derby.sys.tables.Systables;
import org.jooq.meta.derby.sys.tables.Sysviews;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Sys extends SchemaImpl {

  private static final long serialVersionUID = -2021070810;

  /** The reference instance of <code>SYS</code> */
  public static final Sys SYS = new Sys();

  /** The table <code>SYS.SYSCHECKS</code>. */
  public final Syschecks SYSCHECKS = Syschecks.SYSCHECKS;

  /** The table <code>SYS.SYSCOLUMNS</code>. */
  public final Syscolumns SYSCOLUMNS = Syscolumns.SYSCOLUMNS;

  /** The table <code>SYS.SYSCONGLOMERATES</code>. */
  public final Sysconglomerates SYSCONGLOMERATES = Sysconglomerates.SYSCONGLOMERATES;

  /** The table <code>SYS.SYSCONSTRAINTS</code>. */
  public final Sysconstraints SYSCONSTRAINTS = Sysconstraints.SYSCONSTRAINTS;

  /** The table <code>SYS.SYSKEYS</code>. */
  public final Syskeys SYSKEYS = Syskeys.SYSKEYS;

  /** The table <code>SYS.SYSSCHEMAS</code>. */
  public final Sysschemas SYSSCHEMAS = Sysschemas.SYSSCHEMAS;

  /** The table <code>SYS.SYSSEQUENCES</code>. */
  public final Syssequences SYSSEQUENCES = Syssequences.SYSSEQUENCES;

  /** The table <code>SYS.SYSTABLES</code>. */
  public final Systables SYSTABLES = Systables.SYSTABLES;

  /** The table <code>SYS.SYSVIEWS</code>. */
  public final Sysviews SYSVIEWS = Sysviews.SYSVIEWS;

  /** No further instances allowed */
  private Sys() {
    super("SYS", null);
  }

  @Override
  public Catalog getCatalog() {
    return DefaultCatalog.DEFAULT_CATALOG;
  }

  @Override
  public final List<Table<?>> getTables() {
    return Arrays.<Table<?>>asList(
        Syschecks.SYSCHECKS,
        Syscolumns.SYSCOLUMNS,
        Sysconglomerates.SYSCONGLOMERATES,
        Sysconstraints.SYSCONSTRAINTS,
        Syskeys.SYSKEYS,
        Sysschemas.SYSSCHEMAS,
        Syssequences.SYSSEQUENCES,
        Systables.SYSTABLES,
        Sysviews.SYSVIEWS);
  }
}
